<?php

namespace App\DataTables;

use App\Models\post;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
use Yajra\DataTables\DataTablesEditor;


class postsDataTableEditor extends DataTablesEditor
{
    protected $model = post::class;

    /**
     * Get create action validation rules.
     *
     * @return array
     */
    public function createRules()
    {
        return [
            'userId' => 'required|:' . $this->resolveModel()->getTable(),
            'title'  => 'required',
        ];
    }

    /**
     * Get edit action validation rules.
     *
     * @param Model $model
     * @return array
     */
    public function editRules(Model $model)
    {
        return [
            'userId' => 'sometimes|required|',
            'title'  => 'sometimes|required',
        ];
    }

    /**
     * Get remove action validation rules.
     *
     * @param Model $model
     * @return array
     */
    public function removeRules(Model $model)
    {
        return [];
    }

//    public function upload(Request $request)
//    {
////        return parent::upload($request); // TODO: Change the autogenerated stub
//
//        $request->validate($this->uploadRules());
//
//        $type = $request->input('uploadField');
//        $dir  = $this->uploadDir . $type;
//
//        $uploadedFile = $request->file('upload');
//        $filename     = time() . '.png';
//
//        $uploadedFile->move(public_path($dir), $filename);
//
//        $method = 'optimize' . Str::title($type);
//        if (method_exists($this, $method)) {
//            $id = $this->{$method}($dir, $filename);
//        } else {
//            $id = $this->optimize($dir, $filename);
//        }
//
//        return response()->json([
//            'data'   => [],
//            'upload' => [
//                'id' => $id,
//            ],
//        ]);
//
//    }

}
